name: Build APK
 
on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          unzip \
          build-essential \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          liblzma-dev \
          libgdbm-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libgtk-3-dev \
          pkg-config \
          autoconf \
          automake \
          libtool \
          zlib1g-dev \
          libjpeg-dev \
          libc6-dev
        pip install --upgrade pip
        pip install buildozer cython
 
    - name: Init Buildozer (only if missing)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        else
          echo "buildozer.spec already exists, skipping init."
        fi
 
    - name: Build APK
      run: buildozer android debug
 
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
